# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.image_path_te = QtWidgets.QLineEdit(self.tab)
        self.image_path_te.setObjectName("image_path_te")
        self.gridLayout_3.addWidget(self.image_path_te, 0, 0, 1, 1)
        self.infer_bn = QtWidgets.QPushButton(self.tab)
        self.infer_bn.setObjectName("infer_bn")
        self.gridLayout_3.addWidget(self.infer_bn, 0, 5, 1, 1)
        self.open_bn = QtWidgets.QPushButton(self.tab)
        self.open_bn.setObjectName("open_bn")
        self.gridLayout_3.addWidget(self.open_bn, 0, 1, 1, 1)
        self.screen_bn = QtWidgets.QPushButton(self.tab)
        self.screen_bn.setObjectName("screen_bn")
        self.gridLayout_3.addWidget(self.screen_bn, 0, 2, 1, 1)
        self.infer_state = QtWidgets.QLabel(self.tab)
        self.infer_state.setMinimumSize(QtCore.QSize(150, 0))
        self.infer_state.setObjectName("infer_state")
        self.gridLayout_3.addWidget(self.infer_state, 0, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.MIPThird_pre = QtWidgets.QLabel(self.groupBox_2)
        self.MIPThird_pre.setObjectName("MIPThird_pre")
        self.gridLayout.addWidget(self.MIPThird_pre, 2, 1, 1, 1)
        self.DIPFirst_pre = QtWidgets.QLabel(self.groupBox_2)
        self.DIPFirst_pre.setObjectName("DIPFirst_pre")
        self.gridLayout.addWidget(self.DIPFirst_pre, 3, 1, 1, 1)
        self.PIPFirst_pre = QtWidgets.QLabel(self.groupBox_2)
        self.PIPFirst_pre.setObjectName("PIPFirst_pre")
        self.gridLayout.addWidget(self.PIPFirst_pre, 1, 1, 1, 1)
        self.Radius_label = QtWidgets.QLabel(self.groupBox_2)
        self.Radius_label.setObjectName("Radius_label")
        self.gridLayout.addWidget(self.Radius_label, 4, 5, 1, 1)
        self.MCPFifth_label = QtWidgets.QLabel(self.groupBox_2)
        self.MCPFifth_label.setObjectName("MCPFifth_label")
        self.gridLayout.addWidget(self.MCPFifth_label, 0, 8, 1, 1)
        self.MCPFirst_pre = QtWidgets.QLabel(self.groupBox_2)
        self.MCPFirst_pre.setObjectName("MCPFirst_pre")
        self.gridLayout.addWidget(self.MCPFirst_pre, 0, 1, 1, 1)
        self.DIPFifth_label = QtWidgets.QLabel(self.groupBox_2)
        self.DIPFifth_label.setObjectName("DIPFifth_label")
        self.gridLayout.addWidget(self.DIPFifth_label, 3, 8, 1, 1)
        self.MCPThird_label = QtWidgets.QLabel(self.groupBox_2)
        self.MCPThird_label.setObjectName("MCPThird_label")
        self.gridLayout.addWidget(self.MCPThird_label, 0, 5, 1, 1)
        self.MCPFirst_label = QtWidgets.QLabel(self.groupBox_2)
        self.MCPFirst_label.setObjectName("MCPFirst_label")
        self.gridLayout.addWidget(self.MCPFirst_label, 0, 2, 1, 1)
        self.MIPFifth_label = QtWidgets.QLabel(self.groupBox_2)
        self.MIPFifth_label.setObjectName("MIPFifth_label")
        self.gridLayout.addWidget(self.MIPFifth_label, 2, 5, 1, 1)
        self.PIPThird_label = QtWidgets.QLabel(self.groupBox_2)
        self.PIPThird_label.setObjectName("PIPThird_label")
        self.gridLayout.addWidget(self.PIPThird_label, 1, 5, 1, 1)
        self.MIPThird_label = QtWidgets.QLabel(self.groupBox_2)
        self.MIPThird_label.setObjectName("MIPThird_label")
        self.gridLayout.addWidget(self.MIPThird_label, 2, 2, 1, 1)
        self.DIPThird_label = QtWidgets.QLabel(self.groupBox_2)
        self.DIPThird_label.setObjectName("DIPThird_label")
        self.gridLayout.addWidget(self.DIPThird_label, 3, 5, 1, 1)
        self.PIPFifth_label = QtWidgets.QLabel(self.groupBox_2)
        self.PIPFifth_label.setObjectName("PIPFifth_label")
        self.gridLayout.addWidget(self.PIPFifth_label, 1, 8, 1, 1)
        self.Ulna_pre = QtWidgets.QLabel(self.groupBox_2)
        self.Ulna_pre.setObjectName("Ulna_pre")
        self.gridLayout.addWidget(self.Ulna_pre, 4, 1, 1, 1)
        self.PIPFirst_label = QtWidgets.QLabel(self.groupBox_2)
        self.PIPFirst_label.setObjectName("PIPFirst_label")
        self.gridLayout.addWidget(self.PIPFirst_label, 1, 2, 1, 1)
        self.Ulna_label = QtWidgets.QLabel(self.groupBox_2)
        self.Ulna_label.setObjectName("Ulna_label")
        self.gridLayout.addWidget(self.Ulna_label, 4, 2, 1, 1)
        self.DIPFirst_label = QtWidgets.QLabel(self.groupBox_2)
        self.DIPFirst_label.setObjectName("DIPFirst_label")
        self.gridLayout.addWidget(self.DIPFirst_label, 3, 2, 1, 1)
        self.PIPThird_pre = QtWidgets.QLabel(self.groupBox_2)
        self.PIPThird_pre.setObjectName("PIPThird_pre")
        self.gridLayout.addWidget(self.PIPThird_pre, 1, 4, 1, 1)
        self.MIPFifth_pre = QtWidgets.QLabel(self.groupBox_2)
        self.MIPFifth_pre.setObjectName("MIPFifth_pre")
        self.gridLayout.addWidget(self.MIPFifth_pre, 2, 4, 1, 1)
        self.DIPThird_pre = QtWidgets.QLabel(self.groupBox_2)
        self.DIPThird_pre.setObjectName("DIPThird_pre")
        self.gridLayout.addWidget(self.DIPThird_pre, 3, 4, 1, 1)
        self.Radius_pre = QtWidgets.QLabel(self.groupBox_2)
        self.Radius_pre.setObjectName("Radius_pre")
        self.gridLayout.addWidget(self.Radius_pre, 4, 4, 1, 1)
        self.MCPThird_pre = QtWidgets.QLabel(self.groupBox_2)
        self.MCPThird_pre.setObjectName("MCPThird_pre")
        self.gridLayout.addWidget(self.MCPThird_pre, 0, 4, 1, 1)
        self.MCPFifth_pre = QtWidgets.QLabel(self.groupBox_2)
        self.MCPFifth_pre.setObjectName("MCPFifth_pre")
        self.gridLayout.addWidget(self.MCPFifth_pre, 0, 7, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sexBx = QtWidgets.QComboBox(self.groupBox_2)
        self.sexBx.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sexBx.setFont(font)
        self.sexBx.setObjectName("sexBx")
        self.sexBx.addItem("")
        self.sexBx.addItem("")
        self.horizontalLayout_2.addWidget(self.sexBx)
        self.create_bn = QtWidgets.QPushButton(self.groupBox_2)
        self.create_bn.setObjectName("create_bn")
        self.horizontalLayout_2.addWidget(self.create_bn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 8, 1, 1)
        self.PIPFifth_pre = QtWidgets.QLabel(self.groupBox_2)
        self.PIPFifth_pre.setObjectName("PIPFifth_pre")
        self.gridLayout.addWidget(self.PIPFifth_pre, 1, 7, 1, 1)
        self.DIPFifth_pre = QtWidgets.QLabel(self.groupBox_2)
        self.DIPFifth_pre.setObjectName("DIPFifth_pre")
        self.gridLayout.addWidget(self.DIPFifth_pre, 3, 7, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.MCPFirst_text = QtWidgets.QLabel(self.groupBox_2)
        self.MCPFirst_text.setObjectName("MCPFirst_text")
        self.verticalLayout_4.addWidget(self.MCPFirst_text)
        self.MCPFirst_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MCPFirst_cbox.setFont(font)
        self.MCPFirst_cbox.setObjectName("MCPFirst_cbox")
        self.verticalLayout_4.addWidget(self.MCPFirst_cbox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.MCPThird_text = QtWidgets.QLabel(self.groupBox_2)
        self.MCPThird_text.setObjectName("MCPThird_text")
        self.verticalLayout_5.addWidget(self.MCPThird_text)
        self.MCPThird_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MCPThird_cbox.setFont(font)
        self.MCPThird_cbox.setObjectName("MCPThird_cbox")
        self.verticalLayout_5.addWidget(self.MCPThird_cbox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.MCPFifth_text = QtWidgets.QLabel(self.groupBox_2)
        self.MCPFifth_text.setObjectName("MCPFifth_text")
        self.verticalLayout_6.addWidget(self.MCPFifth_text)
        self.MCPFifth_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MCPFifth_cbox.setFont(font)
        self.MCPFifth_cbox.setObjectName("MCPFifth_cbox")
        self.verticalLayout_6.addWidget(self.MCPFifth_cbox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 6, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.PIPFirst_text = QtWidgets.QLabel(self.groupBox_2)
        self.PIPFirst_text.setObjectName("PIPFirst_text")
        self.verticalLayout_7.addWidget(self.PIPFirst_text)
        self.PIPFirst_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PIPFirst_cbox.setFont(font)
        self.PIPFirst_cbox.setObjectName("PIPFirst_cbox")
        self.verticalLayout_7.addWidget(self.PIPFirst_cbox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.gridLayout.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.PIPThird_text = QtWidgets.QLabel(self.groupBox_2)
        self.PIPThird_text.setObjectName("PIPThird_text")
        self.verticalLayout_8.addWidget(self.PIPThird_text)
        self.PIPThird_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PIPThird_cbox.setFont(font)
        self.PIPThird_cbox.setObjectName("PIPThird_cbox")
        self.verticalLayout_8.addWidget(self.PIPThird_cbox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 3, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.PIPFifth_text = QtWidgets.QLabel(self.groupBox_2)
        self.PIPFifth_text.setObjectName("PIPFifth_text")
        self.verticalLayout_9.addWidget(self.PIPFifth_text)
        self.PIPFifth_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PIPFifth_cbox.setFont(font)
        self.PIPFifth_cbox.setObjectName("PIPFifth_cbox")
        self.verticalLayout_9.addWidget(self.PIPFifth_cbox)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 6, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.MIPThird_text = QtWidgets.QLabel(self.groupBox_2)
        self.MIPThird_text.setObjectName("MIPThird_text")
        self.verticalLayout_10.addWidget(self.MIPThird_text)
        self.MIPThird_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MIPThird_cbox.setFont(font)
        self.MIPThird_cbox.setObjectName("MIPThird_cbox")
        self.verticalLayout_10.addWidget(self.MIPThird_cbox)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem14)
        self.gridLayout.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem15)
        self.MIPFifth_text = QtWidgets.QLabel(self.groupBox_2)
        self.MIPFifth_text.setObjectName("MIPFifth_text")
        self.verticalLayout_11.addWidget(self.MIPFifth_text)
        self.MIPFifth_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MIPFifth_cbox.setFont(font)
        self.MIPFifth_cbox.setObjectName("MIPFifth_cbox")
        self.verticalLayout_11.addWidget(self.MIPFifth_cbox)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem16)
        self.gridLayout.addLayout(self.verticalLayout_11, 2, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.DIPFirst_text = QtWidgets.QLabel(self.groupBox_2)
        self.DIPFirst_text.setObjectName("DIPFirst_text")
        self.verticalLayout_12.addWidget(self.DIPFirst_text)
        self.DIPFirst_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DIPFirst_cbox.setFont(font)
        self.DIPFirst_cbox.setObjectName("DIPFirst_cbox")
        self.verticalLayout_12.addWidget(self.DIPFirst_cbox)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem18)
        self.gridLayout.addLayout(self.verticalLayout_12, 3, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem19)
        self.DIPThird_text = QtWidgets.QLabel(self.groupBox_2)
        self.DIPThird_text.setObjectName("DIPThird_text")
        self.verticalLayout_13.addWidget(self.DIPThird_text)
        self.DIPThird_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DIPThird_cbox.setFont(font)
        self.DIPThird_cbox.setObjectName("DIPThird_cbox")
        self.verticalLayout_13.addWidget(self.DIPThird_cbox)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem20)
        self.gridLayout.addLayout(self.verticalLayout_13, 3, 3, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        self.DIPFifth_text = QtWidgets.QLabel(self.groupBox_2)
        self.DIPFifth_text.setObjectName("DIPFifth_text")
        self.verticalLayout_14.addWidget(self.DIPFifth_text)
        self.DIPFifth_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DIPFifth_cbox.setFont(font)
        self.DIPFifth_cbox.setObjectName("DIPFifth_cbox")
        self.verticalLayout_14.addWidget(self.DIPFifth_cbox)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.gridLayout.addLayout(self.verticalLayout_14, 3, 6, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem23)
        self.Ulna_text = QtWidgets.QLabel(self.groupBox_2)
        self.Ulna_text.setObjectName("Ulna_text")
        self.verticalLayout_15.addWidget(self.Ulna_text)
        self.Ulna_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Ulna_cbox.setFont(font)
        self.Ulna_cbox.setObjectName("Ulna_cbox")
        self.verticalLayout_15.addWidget(self.Ulna_cbox)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem24)
        self.gridLayout.addLayout(self.verticalLayout_15, 4, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem25)
        self.Radius_text = QtWidgets.QLabel(self.groupBox_2)
        self.Radius_text.setObjectName("Radius_text")
        self.verticalLayout_16.addWidget(self.Radius_text)
        self.Radius_cbox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Radius_cbox.setFont(font)
        self.Radius_cbox.setObjectName("Radius_cbox")
        self.verticalLayout_16.addWidget(self.Radius_cbox)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem26)
        self.gridLayout.addLayout(self.verticalLayout_16, 4, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.describe_te = QtWidgets.QTextEdit(self.groupBox)
        self.describe_te.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.describe_te.setObjectName("describe_te")
        self.gridLayout_5.addWidget(self.describe_te, 0, 0, 1, 1)
        self.describe_bn = QtWidgets.QPushButton(self.groupBox)
        self.describe_bn.setObjectName("describe_bn")
        self.gridLayout_5.addWidget(self.describe_bn, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gpu_rb = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gpu_rb.setFont(font)
        self.gpu_rb.setObjectName("gpu_rb")
        self.horizontalLayout.addWidget(self.gpu_rb)
        self.nogpu_rb = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nogpu_rb.setFont(font)
        self.nogpu_rb.setChecked(True)
        self.nogpu_rb.setObjectName("nogpu_rb")
        self.horizontalLayout.addWidget(self.nogpu_rb)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem27)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.threshold_value = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.threshold_value.setFont(font)
        self.threshold_value.setObjectName("threshold_value")
        self.horizontalLayout_6.addWidget(self.threshold_value)
        self.threshold_hs = QtWidgets.QSlider(self.groupBox_3)
        self.threshold_hs.setMaximumSize(QtCore.QSize(400, 16777215))
        self.threshold_hs.setMinimum(1)
        self.threshold_hs.setMaximum(9)
        self.threshold_hs.setSliderPosition(2)
        self.threshold_hs.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_hs.setObjectName("threshold_hs")
        self.horizontalLayout_6.addWidget(self.threshold_hs)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_13.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.grade_line_width = QtWidgets.QLabel(self.groupBox_4)
        self.grade_line_width.setObjectName("grade_line_width")
        self.horizontalLayout_5.addWidget(self.grade_line_width)
        self.grade_width_hs = QtWidgets.QSlider(self.groupBox_4)
        self.grade_width_hs.setMaximumSize(QtCore.QSize(400, 16777215))
        self.grade_width_hs.setMinimum(10)
        self.grade_width_hs.setMaximum(150)
        self.grade_width_hs.setSliderPosition(70)
        self.grade_width_hs.setOrientation(QtCore.Qt.Horizontal)
        self.grade_width_hs.setObjectName("grade_width_hs")
        self.horizontalLayout_5.addWidget(self.grade_width_hs)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem29)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.pre_line_width = QtWidgets.QLabel(self.groupBox_4)
        self.pre_line_width.setObjectName("pre_line_width")
        self.horizontalLayout_7.addWidget(self.pre_line_width)
        self.pre_width_hs = QtWidgets.QSlider(self.groupBox_4)
        self.pre_width_hs.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pre_width_hs.setMinimum(50)
        self.pre_width_hs.setMaximum(250)
        self.pre_width_hs.setSliderPosition(100)
        self.pre_width_hs.setOrientation(QtCore.Qt.Horizontal)
        self.pre_width_hs.setObjectName("pre_width_hs")
        self.horizontalLayout_7.addWidget(self.pre_width_hs)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem30)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_l = QtWidgets.QLabel(self.groupBox_4)
        self.label_l.setObjectName("label_l")
        self.horizontalLayout_8.addWidget(self.label_l)
        self.label_line_width = QtWidgets.QLabel(self.groupBox_4)
        self.label_line_width.setObjectName("label_line_width")
        self.horizontalLayout_8.addWidget(self.label_line_width)
        self.label_width_hs = QtWidgets.QSlider(self.groupBox_4)
        self.label_width_hs.setMaximumSize(QtCore.QSize(400, 16777215))
        self.label_width_hs.setMinimum(50)
        self.label_width_hs.setMaximum(500)
        self.label_width_hs.setSliderPosition(360)
        self.label_width_hs.setOrientation(QtCore.Qt.Horizontal)
        self.label_width_hs.setObjectName("label_width_hs")
        self.horizontalLayout_8.addWidget(self.label_width_hs)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem31)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.font_size_lable = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.font_size_lable.setFont(font)
        self.font_size_lable.setObjectName("font_size_lable")
        self.horizontalLayout_9.addWidget(self.font_size_lable)
        self.font_size_hs = QtWidgets.QSlider(self.groupBox_5)
        self.font_size_hs.setMaximumSize(QtCore.QSize(400, 16777215))
        self.font_size_hs.setMinimum(5)
        self.font_size_hs.setMaximum(30)
        self.font_size_hs.setProperty("value", 14)
        self.font_size_hs.setOrientation(QtCore.Qt.Horizontal)
        self.font_size_hs.setObjectName("font_size_hs")
        self.horizontalLayout_9.addWidget(self.font_size_hs)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem32)
        self.verticalLayout_19.addLayout(self.horizontalLayout_9)
        self.gridLayout_15.addLayout(self.verticalLayout_19, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clipboard_cb = QtWidgets.QCheckBox(self.groupBox_6)
        self.clipboard_cb.setObjectName("clipboard_cb")
        self.horizontalLayout_3.addWidget(self.clipboard_cb)
        self.verticalLayout_17.addLayout(self.horizontalLayout_3)
        self.gridLayout_16.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem33)
        self.sure_bn = QtWidgets.QPushButton(self.tab_3)
        self.sure_bn.setObjectName("sure_bn")
        self.horizontalLayout_4.addWidget(self.sure_bn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_14.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem34, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1216, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionWarm = QtWidgets.QAction(MainWindow)
        self.actionWarm.setObjectName("actionWarm")
        self.actionIsgpu = QtWidgets.QAction(MainWindow)
        self.actionIsgpu.setObjectName("actionIsgpu")
        self.actionTheshold = QtWidgets.QAction(MainWindow)
        self.actionTheshold.setObjectName("actionTheshold")
        self.actionProject = QtWidgets.QAction(MainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionWhole = QtWidgets.QAction(MainWindow)
        self.actionWhole.setObjectName("actionWhole")
        self.actionRUS_CHN = QtWidgets.QAction(MainWindow)
        self.actionRUS_CHN.setObjectName("actionRUS_CHN")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionClose)
        self.menu_2.addAction(self.actionWarm)
        self.menu_3.addAction(self.actionAbout)
        self.menu_4.addAction(self.actionWhole)
        self.menu_4.addAction(self.actionRUS_CHN)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infer_bn.setText(_translate("MainWindow", "推理"))
        self.open_bn.setText(_translate("MainWindow", "打开"))
        self.screen_bn.setText(_translate("MainWindow", "截图"))
        self.infer_state.setText(_translate("MainWindow", "推理状态:无"))
        self.groupBox_2.setTitle(_translate("MainWindow", "展示推理"))
        self.MIPThird_pre.setText(_translate("MainWindow", "TextLabel"))
        self.DIPFirst_pre.setText(_translate("MainWindow", "TextLabel"))
        self.PIPFirst_pre.setText(_translate("MainWindow", "TextLabel"))
        self.Radius_label.setText(_translate("MainWindow", "TextLabel"))
        self.MCPFifth_label.setText(_translate("MainWindow", "TextLabel"))
        self.MCPFirst_pre.setText(_translate("MainWindow", "TextLabel"))
        self.DIPFifth_label.setText(_translate("MainWindow", "TextLabel"))
        self.MCPThird_label.setText(_translate("MainWindow", "TextLabel"))
        self.MCPFirst_label.setText(_translate("MainWindow", "TextLabel"))
        self.MIPFifth_label.setText(_translate("MainWindow", "TextLabel"))
        self.PIPThird_label.setText(_translate("MainWindow", "TextLabel"))
        self.MIPThird_label.setText(_translate("MainWindow", "TextLabel"))
        self.DIPThird_label.setText(_translate("MainWindow", "TextLabel"))
        self.PIPFifth_label.setText(_translate("MainWindow", "TextLabel"))
        self.Ulna_pre.setText(_translate("MainWindow", "TextLabel"))
        self.PIPFirst_label.setText(_translate("MainWindow", "TextLabel"))
        self.Ulna_label.setText(_translate("MainWindow", "TextLabel"))
        self.DIPFirst_label.setText(_translate("MainWindow", "TextLabel"))
        self.PIPThird_pre.setText(_translate("MainWindow", "TextLabel"))
        self.MIPFifth_pre.setText(_translate("MainWindow", "TextLabel"))
        self.DIPThird_pre.setText(_translate("MainWindow", "TextLabel"))
        self.Radius_pre.setText(_translate("MainWindow", "TextLabel"))
        self.MCPThird_pre.setText(_translate("MainWindow", "TextLabel"))
        self.MCPFifth_pre.setText(_translate("MainWindow", "TextLabel"))
        self.sexBx.setItemText(0, _translate("MainWindow", "boy"))
        self.sexBx.setItemText(1, _translate("MainWindow", "girl"))
        self.create_bn.setText(_translate("MainWindow", "生成报告"))
        self.PIPFifth_pre.setText(_translate("MainWindow", "TextLabel"))
        self.DIPFifth_pre.setText(_translate("MainWindow", "TextLabel"))
        self.MCPFirst_text.setText(_translate("MainWindow", "TextLabel"))
        self.MCPThird_text.setText(_translate("MainWindow", "TextLabel"))
        self.MCPFifth_text.setText(_translate("MainWindow", "TextLabel"))
        self.PIPFirst_text.setText(_translate("MainWindow", "TextLabel"))
        self.PIPThird_text.setText(_translate("MainWindow", "TextLabel"))
        self.PIPFifth_text.setText(_translate("MainWindow", "TextLabel"))
        self.MIPThird_text.setText(_translate("MainWindow", "TextLabel"))
        self.MIPFifth_text.setText(_translate("MainWindow", "TextLabel"))
        self.DIPFirst_text.setText(_translate("MainWindow", "TextLabel"))
        self.DIPThird_text.setText(_translate("MainWindow", "TextLabel"))
        self.DIPFifth_text.setText(_translate("MainWindow", "TextLabel"))
        self.Ulna_text.setText(_translate("MainWindow", "TextLabel"))
        self.Radius_text.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "AI推理区"))
        self.groupBox.setTitle(_translate("MainWindow", "报告区"))
        self.describe_bn.setText(_translate("MainWindow", "复制全文"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "报告区"))
        self.groupBox_3.setTitle(_translate("MainWindow", "参数设置"))
        self.label.setText(_translate("MainWindow", "使用GPU"))
        self.gpu_rb.setText(_translate("MainWindow", "是"))
        self.nogpu_rb.setText(_translate("MainWindow", "否"))
        self.label_2.setText(_translate("MainWindow", "阈值:"))
        self.threshold_value.setText(_translate("MainWindow", "0.1"))
        self.groupBox_4.setTitle(_translate("MainWindow", "预测展示设置"))
        self.label_4.setText(_translate("MainWindow", "等级本文宽度："))
        self.grade_line_width.setText(_translate("MainWindow", "50"))
        self.label_5.setText(_translate("MainWindow", "预测展示宽度："))
        self.pre_line_width.setText(_translate("MainWindow", "100"))
        self.label_l.setText(_translate("MainWindow", "图谱展示宽度："))
        self.label_line_width.setText(_translate("MainWindow", "360"))
        self.groupBox_5.setTitle(_translate("MainWindow", "报告显示设置"))
        self.label_3.setText(_translate("MainWindow", "字体大小:"))
        self.font_size_lable.setText(_translate("MainWindow", "14"))
        self.groupBox_6.setTitle(_translate("MainWindow", "其他设置"))
        self.clipboard_cb.setText(_translate("MainWindow", "使用剪贴板获取图片(注意需要特定PACS系统才能使用)"))
        self.sure_bn.setText(_translate("MainWindow", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "设置区"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "模型"))
        self.menu_3.setTitle(_translate("MainWindow", "其他"))
        self.menu_4.setTitle(_translate("MainWindow", "图谱"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionWarm.setText(_translate("MainWindow", "模型预热"))
        self.actionIsgpu.setText(_translate("MainWindow", "GPU关"))
        self.actionTheshold.setText(_translate("MainWindow", "阈值"))
        self.actionProject.setText(_translate("MainWindow", "关于项目"))
        self.actionAuthor.setText(_translate("MainWindow", "关于作者"))
        self.actionWhole.setText(_translate("MainWindow", "骨龄标准整片图谱"))
        self.actionRUS_CHN.setText(_translate("MainWindow", "RUS_CHN图谱"))
        self.actionAbout.setText(_translate("MainWindow", "关于此项目"))

